### ISSUE TITLE
Weird problem

### ISSUE THREAD

**Issue by x60hz11** [djp952/hdhomeruntray#52]
Hey Michael, long time. But let that be a testimate to how well your addon has been working! 
So a weird thing happened a couple of days ago. I was not able to watch any recordings that I had made with the add-on. I was getting a record stream not created error. At that point I then realized that my rewind and fast forward features on live TV were not working as well. This led me to believe that there was a problem with the HD home run record engine. I checked this and rebooted both the Kodi software and the raspberry pi it was running on. After the system rebooted I was having the same problem. I then decided to uninstall the add-on and after reinstalling it it refuses to now see the tuner at all. The other TVs I have in the house running the add-on do seem to work however the rewind and fast forward buttons do not work. Also I should mention that the HD native software and HD home run stock add-on do work, but as you know they don't support time shifting or pause and rewinding of live TV. You got me on this one buddy.  Thanx, Joe

**Comment by djp952** [comment]
Yeah, SiliconDust decided to suddenly change the entire backend without any notice; I'm scrambling to catch up.  There are two groups of problems rendering the addon useless --  Issue 1 is that SSL/TLS is now required for all the backend API calls (what I'm working on now), and Issue 2 is that the latest firmware/software updates messed up timeshifting (among other things).  I haven't updated my tuners/RECORD yet while I deal with Issue 1 :(

All I can do is apologize; I actually took a legit vacation for the first time in 2 years and while I was gone this happened :(  

I won't say as much on the SD forums, but I'm pretty pissed off here, breaking everything but your own app without any notice whatsoever while saying you are an "open" ecosystem is BS.

Sadly this is not a quick-fix, but I am indeed pushing through it.  "Major surgery" would be an understatement.

Hang tight if you can, best guess is 3-4 days (for real)

**Comment by x60hz11** [comment]
That actually eases my mind. At least it's not something that I screwed up lol. Also, I wouldn't exactly say that the add-on is useless.

**Comment by x60hz11** [comment]
Hey Mike, Just wanted to say thank you!! I noticed you posted the new rev up. So I tried it and it works like a charm!! I hope and pray you decide to never stop supporting this lol. I can't understand why SD won't support this or even buy it. I mean I guess they do to an extent but none of their software supports time shifting. Any good DVR would do that! Not to mention their guide absolutely sucks. And as far as I'm concerned there's nothing else out there that even comes close to what you've done. Thanks again! I still wish you'd open a PayPal or donation page so all of us Zuki users can at least send you some token of gratitude!!Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Michael Brehm ***@***.***> Date: 1/29/22  10:01 PM  (GMT-05:00) To: djp952/hdhomeruntray ***@***.***> Cc: x60hz11 ***@***.***>, Author ***@***.***> Subject: Re: [djp952/hdhomeruntray] Weird problem (Issue #52) 
Yeah, SiliconDust decided to suddenly change the entire backend without any notice; I'm scrambling to catch up.  There are two groups of problems rendering the addon useless --  Issue 1 is that SSL/TLS is now required for all the backend API calls (what I'm working on now), and Issue 2 is that the latest firmware/software updates messed up timeshifting (among other things).  I haven't updated my tuners/RECORD yet while I deal with Issue 1 :(
All I can do is apologize; I actually took a legit vacation for the first time in 2 years and while I was gone this happened :(
I won't say as much on the SD forums, but I'm pretty pissed off here, breaking everything but your own app without any notice whatsoever while saying you are an "open" ecosystem is BS.
Sadly this is not a quick-fix, but I am indeed pushing through it.  "Major surgery" would be an understatement.
Hang tight if you can, best guess is 3-4 days (for real)

**Comment by djp952** [comment]
All things must eventually come to an end, but my day job sucks so hard right now it was (kind of absurdly?) pleasing to have to retool an otherwise really darn stable project out of the blue, if that makes sense? :)

The goal was, and still is, just to share what I ended up doing for myself and made me happy with the ecosystem :).  It will get old at some point, I mean, I've asked SiliconDust a number of times if they want me to just cede the project to them to maintain, and they really don't seem to care :(

Totally agree with that damn "Slice UI" concept instead of a proper EPG, I really wish they would give up on that; I think their software userbase would increase 10x just from that.  The patents involved have been legally proven to be non-enforceable, but yet SD still considers the topic to be taboo in nature.  sigh.

I hope you don't mind, but I will go ahead and close this Issue since you're "good" now after the update.  Please do not hesitate to reopen and/or add new Issues for me, it's kind of what I'm here for my friend :)

**Comment by x60hz11** [comment]
It’s such a shame they show no interest. It really is a lucid, useful piece of coding. Let me ask you, is this written in Python? As a VB.net and LISP coder for AutoCAD (my daytime gig), I have an appetite for destruction in the form of coding 😊. I would love to learn the nuts and bolts of these addons. I have zero experience with Python and am aware of the resources on the web but is there anything particular you could recommend?

**Comment by djp952** [comment]
Actually, PVR addons are all done in C++ they are considered as "binary" addons like some of the other lower-level types (input streams, file systems, etc).  I think a number of years ago Kodi wanted to move PVR into Python but almost all of them require use of C/C++ libraries so I think the bang for the buck wasn't there.

I'll admit I've not done ANYTHING in Python, like ever.  OK, I fixed the old HDHomeRun Python-based addon for NedS at SD a couple times, but that was a real struggle.  Maybe have a look at a video addon?  There is an open source one for Sling that's pretty extensive: https://github.com/d21spike/plugin.video.sling.  He/she even has it interface with the IPTV PVR addon to feed guide data into Kodi that way.  A bit convoluted IMO as opposed to just making a PVR addon, but hey - it works!
