### ISSUE TITLE
Border in dark mode is slight too wide.

### ISSUE THREAD

**Issue by irctrakz** [djp952/hdhomeruntray#54]
Ok, I'm sorry ( I love this thing), but can the border size be reduced (or configurable?), basically 1px should be enough?

In dark mode it's especially large, and (for me) ruins the aesthetic of the taskbar area.

Thank you for all the work. This continues to be awfully useful!

**Comment by djp952** [comment]
There are a handful of things in the pipeline for stuff like this that I haven't been able to release yet, but just so I can make sure I see it, are you on Windows 7, Windows 10, or Windows 11?  The (unreleased) latest should have a 1px border on both Windows 10 and Windows 11 now, but I honestly forget if I applied the same to Windows 7.

SiliconDust broke my Kodi PVR addon on me while I was on vacation and I'm scrambling to fix that first :(

**Comment by irctrakz** [comment]
Windows 10 - but I switched from building it myself to using your releases :-)

**Comment by djp952** [comment]
Hi!  Sorry for needing to take an extended break from this, trying to get this finished up for everyone.  Here is a screenshot of the app in Dark Mode on Windows 10 as I had left it, does this work OK for you?

![Screenshot 2022-03-04 210228](https://user-images.githubusercontent.com/706055/156863414-0b16288c-828a-4028-a6ce-9bc2513efb2e.png)

**Comment by irctrakz** [comment]
Perfect - thank you!

**Comment by djp952** [comment]
Awesome!  You can grab version 0.9.9 right now, which has this change: https://github.com/djp952/hdhomeruntray/releases/tag/0.9.9.
