### ISSUE TITLE
Add a donate/buy me coffee button on git

### ISSUE THREAD

**Issue by irctrakz** [djp952/hdhomeruntray#55]
I'd like to contribute a few $$ to the success of this, please add a button to do so.

**Comment by djp952** [comment]
While I **very sincerely** appreciate the thought/consideration here, I (currently still) have a very strict rule about donations -- I do not accept them.  I have a well-paying day job; anything out here is totally pro-bono and is legitimately intended as a "for the greater good" type of thing.

These open-source projects help to maintain my overall sanity and allow me to continue to flex/grow my technical "muscles", which is not something my day job can accommodate anymore, and quite frankly hasn't been able to for almost a decade :(  The boundaries of this project in particular (target the old .NET 4.6 platform and the legacy Windows Forms platform) has taught me a lot of things I didn't know before, and that is reward enough.

I am sincerely touched by the offer, I really am, but accepting any money and/or goods for these efforts I make would run contrary to the reason(s) I made them.  I hope you can understand my position and do not feel like this is a "slight" in any way.

On the more selfish side of things, keeping everything pro-bono also gives me an easy "out" if I decide to abandon/ignore it :)  You get what you pay for, right?? LOL

**Comment by irctrakz** [comment]
Fair enough. I still think I should probably (at a minimum) buy you a coffee for the value I receive (because it’s all about me!)
