### ISSUE TITLE
Size/Space left under HDHomeRun RECORD does not live update?

### ISSUE THREAD

**Issue by wazerstar** [djp952/hdhomeruntray#66]
Would it be possible to make it pull some sort of live update with Size/Space left whenever one connect/disconnect/change channel under the HDHomeRun RECORD if that engine is used?

I noticed when closing to tray and opening it again it will refresh

Is it possible to do when The hovering gui is active without causing high system resources?

**Comment by wazerstar** [comment]
👍

**Comment by djp952** [comment]
Implemented for version 1.1.0 via https://github.com/djp952/hdhomeruntray/commit/66fa6ff92632f6c64bdf98928f8f6e9cbeecaeee.

Will set a reminder to look this project over and see about a date for that version 1.1.0 for ya :)

**Comment by wazerstar** [comment]
> Implemented for version 1.1.0 via [66fa6ff](https://github.com/djp952/hdhomeruntray/commit/66fa6ff92632f6c64bdf98928f8f6e9cbeecaeee).
> 
> Will set a reminder to look this project over and see about a date for that version 1.1.0 for ya :)

Great :)

**Comment by djp952** [comment]
Hi @waserstar, it didn't seem like I was going to get much (if any) time to work on burning down more of the Issues, so I went ahead and built Version 1.1.0 for ya that has this change in it, so you don't have to keep waiting: https://github.com/djp952/hdhomeruntray/releases/tag/1.1.0.

I hope it does what you want!

Closing via Release v1.1.0.

**Comment by wazerstar** [comment]
> Hi @waserstar, it didn't seem like I was going to get much (if any) time to work on burning down more of the Issues, so I went ahead and built Version 1.1.0 for ya that has this change in it, so you don't have to keep waiting: https://github.com/djp952/hdhomeruntray/releases/tag/1.1.0.
> 
> I hope it does what you want!
> 
> Closing via Release v1.1.0.

Tested and approved, works like a charm :)
